import{a as L,S as w,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(r){if(r.ep)return;r.ep=!0;const t=a(r);fetch(r.href,t)}})();const v=e=>`
        <a href="${e.largeImageURL}">
            <div class="gallery-item">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
                <div class="info">
                    <p>Likes: ${e.likes}</p>
                    <p>Views: ${e.views}</p>
                    <p>Comments: ${e.comments}</p>
                    <p>Downloads: ${e.downloads}</p>
                </div>
            </div>
        </a>`,b="https://pixabay.com",P="46898279-65d5dcdd2fa29fc168f36b5dd",S=async(e,o=1)=>{const a={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await L.get(`${b}/api/`,{params:a})).data}catch(s){throw console.error("Axios error:",s),s}},f=document.querySelector(".search-container"),u=document.querySelector(".galerry-js"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new w(".galerry-js a",{captionsData:"alt",captionDelay:250});let n=1,d="";function p(){m.classList.add("hidden")}function y(){m.classList.remove("hidden")}function E(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const M=async e=>{if(e.preventDefault(),d=f.elements.user_query.value.trim(),n=1,!d){i.warning({title:"Warning",message:"Please enter a search query."});return}u.innerHTML="",c(),y();try{await g()}catch(o){i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."}),console.error(o)}finally{p()}},g=async()=>{try{const e=await S(d,n);if(e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),c();return}const o=e.hits.map(s=>v(s)).join("");u.insertAdjacentHTML("beforeend",o),q.refresh();const a=Math.ceil(e.totalHits/15);n>=a?(i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c()):E(),A(),n+=1}catch(e){console.error(e)}},$=async()=>{y(),c(),await g(),p()},A=()=>{const{height:e}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};f.addEventListener("submit",M);h.addEventListener("click",$);
//# sourceMappingURL=index.js.map
